CASE_NAME := mem_many_areas
CASE_SRCS := root_thread.c
SENTINELS := "mem_many_areas: areas PASS" "mem_many_areas: PASS"
FAIL_SENTINEL := "mem_many_areas: FAIL"
QEMU_TIMEOUT := 40

include ../sdk_case.mk
