#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
Generate CRC-valid SSUMODE2 SECCFG binaries for F29H85x BANKMODE0.

Starts from TI SDK default MODE1 SECCFG (zone/debug/stack/link intact),
rewrites APR slots for MODE2 necessary + kernel ranges, sets SSU_MODE=0x0C,
recomputes CRC with the same algorithm as seccfgChecker.py.

Usage:
  tools/c29_seccfg_gen.py --sdk <sdk> --out-dir <dir>
"""

from __future__ import annotations

import argparse
import os
import struct
import subprocess
import sys

SECCFG_SIZE = 2048
SSUMODE_2 = 0x0C
SECCFG_STATUS = 0x55555555
SECCFG_CRC_OFF = 0x7F4
SSU_MODE_OFF = 0x7F8
STATUS1_OFF = 0x7B8
STATUS2_OFF = 0x7BC
APR_STRIDE = 16
NUM_APR = 64

CRC_RANGES = ((0x000, 0x6C0), (0x7A0, 0x7F4), (0x7F8, 0x800))

def load_crc_table(sdk: str) -> list[int]:
	"""Parse crc32Table from TI seccfgChecker.py without executing it."""
	path = os.path.join(sdk, "tools/misc/seccfgChecker.py")
	with open(path, "r", encoding="utf-8") as f:
		src = f.read()
	start = src.index("crc32Table = [")
	end = src.index("]", start)
	body = src[start:end + 1]
	ns: dict = {}
	exec(body, ns)
	return list(ns["crc32Table"])

def compute_crc(data: bytes, table: list[int]) -> int:
	crc = 0xFFFFFFFF
	for start, end in CRC_RANGES:
		for i in range(start, end):
			crc = table[(crc ^ data[i]) & 0xFF] ^ (crc >> 8)
	return crc ^ 0xFFFFFFFF


def pack_apr(start: int, end: int, access: int, *,
	     linkid: int = 2, xe: int = 0, disable: int = 0) -> bytes:
	"""Pack one 16-byte APR matching SSU_SECCFG.AP_REGS bitfields."""
	start_page = (start >> 12) & 0xFFFFF
	end_page = (end >> 12) & 0xFFFFF
	w0 = (start_page << 12)  # LOCK=0
	w1 = (end_page << 12)    # COMMIT=0
	# bytes 12-13 rsvd3 = 0; bytes 14-15 config
	cfg = (linkid & 0xF)
	cfg |= (disable & 1) << 6
	cfg |= (xe & 1) << 7
	# APILINK/APILINKE left 0
	return struct.pack("<IIIHH", w0, w1, access & 0xFFFFFFFF, 0, cfg & 0xFFFF)


def link_rd(link: int) -> int:
	return 1 << (link * 2)


def link_rw(link: int) -> int:
	return 3 << (link * 2)


def fill_aprs(buf: bytearray) -> None:
	# Unused slots: DISABLE=1, LINKID=2 (checker rejects LINKID=0)
	unused = pack_apr(0, 0xFFF, 0, linkid=2, disable=1)
	for i in range(NUM_APR):
		buf[i * APR_STRIDE:(i + 1) * APR_STRIDE] = unused

	# Necessary APRs (seccfgChecker) — Link1 access.
	# Plus kernel/runtime ranges so CPU1 can XIP and use LDA without
	# Link2 AP override after MODE2 boot.
	aprs = [
		# flash cert page (necessary) — L1 RD
		(0x10000000, 0x10000FFF, link_rd(1) | link_rd(2), 1),
		# rest of FLASH_RP0 used by ulmk — L1/L2 RD + XE on L2
		(0x10001000, 0x100FFFFF, link_rd(1) | link_rd(2), 1),
		# PIPE INT CTL / CONFIG / IPC (necessary)
		(0x30226000, 0x30226FFF, link_rw(1) | link_rw(2), 0),
		(0x30227000, 0x30227FFF, link_rw(1) | link_rw(2), 0),
		(0x302C0000, 0x302C1FFF, link_rw(1) | link_rw(2), 0),
		# SSU AP regs CPU1/2/3 (necessary)
		(0x60080000, 0x60080FFF, link_rw(1) | link_rw(2), 0),
		(0x6008C000, 0x6008CFFF, link_rw(1) | link_rw(2), 0),
		(0x60090000, 0x60090FFF, link_rw(1) | link_rw(2), 0),
		# PIPE + SSUGEN MMIO windows used by kernel
		(0x30020000, 0x3002FFFF, link_rw(2), 0),
		(0x30080000, 0x3008FFFF, link_rw(2), 0),
		# LDA / LPA / CPA RAM (kernel + shared + secondary stubs)
		(0x200E0000, 0x200FFFFF, link_rw(1) | link_rw(2), 0),
		(0x20100000, 0x2011FFFF, link_rw(1) | link_rd(2) | link_rw(2), 1),
	]

	for i, (start, end, access, xe) in enumerate(aprs):
		if i >= NUM_APR:
			raise SystemExit("too many APRs")
		buf[i * APR_STRIDE:(i + 1) * APR_STRIDE] = pack_apr(
			start, end, access, linkid=2, xe=xe, disable=0)


def make_mode2(base: bytes, table: list[int]) -> bytes:
	if len(base) != SECCFG_SIZE:
		raise SystemExit(f"bad seccfg size {len(base)}")
	buf = bytearray(base)
	fill_aprs(buf)
	struct.pack_into("<I", buf, SSU_MODE_OFF, SSUMODE_2)
	# Keep SECT_STATUS as 0x55555555 / 0x55555555 (uint64 at 0x7B8)
	struct.pack_into("<I", buf, STATUS1_OFF, SECCFG_STATUS)
	struct.pack_into("<I", buf, STATUS2_OFF, SECCFG_STATUS)
	struct.pack_into("<I", buf, SECCFG_CRC_OFF, 0)
	crc = compute_crc(bytes(buf), table)
	struct.pack_into("<I", buf, SECCFG_CRC_OFF, crc)
	return bytes(buf)


def extract_defaults(objcopy: str, default_out: str, tmp: str) -> dict[int, bytes]:
	os.makedirs(tmp, exist_ok=True)
	out = {}
	for cpu in (1, 2, 3, 4):
		path = os.path.join(tmp, f"cpu{cpu}.bin")
		subprocess.check_call([
			objcopy, "-O", "binary",
			f"--only-section=.TI.bound:CPU{cpu}_Cfg",
			default_out, path,
		])
		out[cpu] = open(path, "rb").read()
	return out


def emit_c_blob(path: str, symbol: str, section: str, data: bytes, addr: int) -> None:
	lines = [
		"/* SPDX-License-Identifier: MIT */",
		f"/* Auto-generated by c29_seccfg_gen.py — do not edit. */",
		"#include <stdint.h>",
		"",
		f"__attribute__((retain, section(\"{section}\")))",
		f"const uint8_t {symbol}[2048] = {{",
	]
	for i in range(0, len(data), 16):
		chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
		lines.append(f"\t{chunk},")
	lines.append("};")
	lines.append("")
	# Keep the linker location via section name; address is in memory_flash.
	_ = addr
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(lines) + "\n")


def main() -> int:
	ap = argparse.ArgumentParser()
	ap.add_argument("--sdk", required=True)
	ap.add_argument("--objcopy", required=True)
	ap.add_argument("--out-dir", required=True)
	ap.add_argument("--check", action="store_true",
			help="run TI seccfgChecker.py on the result")
	args = ap.parse_args()

	default_out = os.path.join(
		args.sdk, "source/defseccfgbin/default_seccfg_bankmode_0_ssumode1.out")
	if not os.path.isfile(default_out):
		print(f"missing {default_out}", file=sys.stderr)
		return 1

	table = load_crc_table(args.sdk)
	tmp = os.path.join(args.out_dir, "_extract")
	bases = extract_defaults(args.objcopy, default_out, tmp)

	os.makedirs(args.out_dir, exist_ok=True)
	# BANKMODE0 NonMain SECCFG placements (TI default map)
	addrs = {1: 0x10D85000, 2: 0x10D85800, 3: 0x10D8D000, 4: 0x10D8D800}
	bins = {}
	for cpu, base in bases.items():
		data = make_mode2(base, table) if cpu == 1 else make_mode2(base, table)
		# CPU2/3/4: same MODE2 + APR rewrite keeps checker happy; CPU2
		# runtime APRs are still local to that core's AP block.
		bins[cpu] = data
		bin_path = os.path.join(args.out_dir, f"seccfg_cpu{cpu}.bin")
		open(bin_path, "wb").write(data)
		emit_c_blob(
			os.path.join(args.out_dir, f"seccfg_cpu{cpu}.c"),
			f"ulmk_c29_seccfg_cpu{cpu}",
			f".TI.bound:CPU{cpu}_Cfg",
			data,
			addrs[cpu],
		)
		print(f"wrote CPU{cpu} MODE={SSUMODE_2:#x} CRC="
		      f"{struct.unpack_from('<I', data, SECCFG_CRC_OFF)[0]:#x}")

	if args.check:
		cwd = args.out_dir
		for cpu in (1, 2, 3, 4):
			src = os.path.join(args.out_dir, f"seccfg_cpu{cpu}.bin")
			dst = os.path.join(cwd, f"seccfgCpu{cpu}.bin")
			open(dst, "wb").write(open(src, "rb").read())
		checker = os.path.join(args.sdk, "tools/misc/seccfgChecker.py")
		# Checker expects seccfgCpu*.bin in CWD and takes objcopy+elf
		# but only reads the bins — pass a dummy elf path.
		r = subprocess.run(
			[sys.executable, checker, args.objcopy, default_out],
			cwd=cwd, capture_output=True, text=True)
		sys.stdout.write(r.stdout)
		sys.stderr.write(r.stderr)
		if "Error count =  0" not in r.stdout and "Error count = 0" not in r.stdout:
			# checker prints "Error count =  0" with two spaces
			if r.returncode != 0 or "SECCFG-ERROR" in r.stdout:
				print("seccfgChecker failed", file=sys.stderr)
				return 1
		print("seccfgChecker: OK")

	return 0


if __name__ == "__main__":
	sys.exit(main())
