#!/usr/bin/env python3
# cmake/generate_ld.py
# Assembles the final linker script from layered fragments.
# Full specification: docs/linker_spec.md §5
#
# Invocation (see linker_api.cmake):
#   generate_ld.py --chip-dir <path> --arch-dir <path> \
#                  --kernel-dir <path> --snippets <path> \
#                  --output <file> \
#                  [--app <name>]... [--comp <name>]... [--domain <name:region>]...
#
# Assembly order:
#   1. arch prologue (arch-dir/prologue.ld.in)
#   2. chip MEMORY block (chip-dir/memory.ld)
#   3. [optional] chip BMHD fragment (chip-dir/bmhd.ld.in, if HAVE_BMHD=1)
#   4. SECTIONS {
#        kernel/vectors.ld.in
#        kernel/kernel_text.ld.in
#        [rendered snippets/comp_text.ld.in  for each --comp]
#        kernel/user_runtime.ld.in
#        [rendered snippets/app_code.ld.in   for each --app]
#        kernel/kernel_data.ld.in
#        kernel/domain_table.ld.in
#        kernel/kernel_stacks.ld.in
#        [arch/tricore/linker/csa_pool.ld.in    if HAVE_CSA=1]
#        [arch/tricore/linker/small_data.ld.in  if HAVE_SMALL_DATA=1]
#        kernel/kernel_ram_end.ld.in
#        kernel/user_ram_start.ld.in
#        [rendered snippets/domain_data.ld.in for each --domain]
#        kernel/isr_stack.ld.in
#        kernel/user_bss.ld.in
#        kernel/user_pool.ld.in
#      }

import argparse
import os
import re
import sys

# ---------------------------------------------------------------------------
# TI C29 .cmd renderer
# ---------------------------------------------------------------------------

_TI_C29_PROLOGUE = """\
/* Generated by cmake/generate_ld.py — TI C29 linker command file.
 * Do not edit manually; changes are overwritten at configure time.
 */
"""

_TI_SECTION_TPLS = {
    "vectors_note": "",
    "all_text": """\

    /* Program: startup vectors already placed; remaining code.
     * .rodata/.const stay in KERNEL_RAM.  Split LPA0→CPA1 — no '.'
     * assignments inside the {} (TI ignores >> when present).
     * LPA1 is CPU2-only; CPA0 is CPU3-only. */
    .text : {
        *(.text)
        *(.text.*)
    } >> KERNEL_FLASH | CPU1_CPA1, RUN_START(_ulmk_kernel_text_start), RUN_END(_ulmk_kernel_text_end)
""",
    "data": """\

    /* RAM-load profile: LMA == VMA (debugger loads .data into RAM). */
    .data : {
        _ulmk_kernel_data_start = .;
        __ulmk_kernel_data_load = .;
        _ulmk_user_data_start = .;
        __ulmk_user_data_load = .;
        *(.data)
        *(.data.*)
        *(.rodata)
        *(.rodata.*)
        *(.const)
        *(.const.*)
        _ulmk_kernel_data_end = .;
        _ulmk_user_data_end = .;
    } > KERNEL_RAM
""",
    "all_text_flash": """\

    /* FLASH profile: code + rodata execute-in-place from flash bank RP0. */
    .text : {
        _ulmk_kernel_text_start = .;
        _ulmk_user_text_start = .;
        *(.text)
        *(.text.*)
        *(.rodata)
        *(.rodata.*)
        *(.const)
        *(.const.*)
        _ulmk_kernel_text_end = .;
        _ulmk_user_text_end = .;
    } > KERNEL_FLASH, palign(8)
""",
    "data_flash": """\

    /* FLASH profile: .data RUNs in RAM, LMA in flash; init.c relocates it.
     * LOAD_START(sym) is a TI section-specifier operator that DEFINES sym as
     * the load (flash) address; init.c copies from there into the run VMA.
     * User data gets its own (empty for kernel-only) section so it has its
     * own LOAD_START symbol without a cross-section assignment. */
    .data : palign(8), load = KERNEL_FLASH, run = KERNEL_RAM, LOAD_START(__ulmk_kernel_data_load) {
        _ulmk_kernel_data_start = .;
        *(.data)
        *(.data.*)
        _ulmk_kernel_data_end = .;
    }
    .ulmk_user_data : palign(8), load = KERNEL_FLASH, run = KERNEL_RAM, LOAD_START(__ulmk_user_data_load) {
        _ulmk_user_data_start = .;
        *(.ulmk_user_data)
        *(.ulmk_user_data.*)
        _ulmk_user_data_end = .;
    }
""",
    "bss": """\

    /* .user_bss is collected here so it always has an explicit placement in
     * data RAM: left unplaced, the TI linker drops it into the first free
     * range, which in the flash profile is the boot certificate area. */
    .bss : {
        _ulmk_kernel_bss_start = .;
        *(.bss)
        *(.bss.*)
        *(COMMON)
        *(.user_bss)
        *(.user_bss.*)
        _ulmk_kernel_bss_end = .;
    } > KERNEL_RAM, type = NOLOAD, palign(8)
""",
    "stacks": """\

    .ulmk_kernel_stacks : {
        _ulmk_kernel_stack_base = .;
        . += ULMK_KERNEL_STACK_SIZE;
        _ulmk_kernel_stack_top = .;
        _ulmk_isr_stack_base = .;
        . += ULMK_ISR_STACK_SIZE;
        _ulmk_isr_stack_top = .;
    } > KERNEL_RAM, type = NOLOAD, palign(8)
""",
    "user_pool": """\

    .ulmk_user_pool : {
        _ulmk_user_pool_start = .;
        . += ULMK_USER_POOL_SIZE;
        _ulmk_user_pool_end = .;
    } > KERNEL_RAM, type = NOLOAD
""",
}


def _render_ti_cmd(args: argparse.Namespace, chip_memory: str) -> str:
    """Render a TI C29 .cmd linker file from chip memory.cmd and templates."""
    sections = []
    flash = getattr(args, "profile", "ram") == "flash"

    vectors_name = "vectors_flash.cmd.in" if flash else "vectors.cmd.in"
    vectors_path = os.path.join(args.arch_dir, vectors_name)
    if not flash and not os.path.exists(vectors_path):
        vectors_path = os.path.join(args.arch_dir, "vectors.cmd.in")
    if os.path.exists(vectors_path):
        sections.append("\n" + read_fragment(vectors_path))

    sections.extend([
        _TI_SECTION_TPLS["all_text_flash" if flash else "all_text"],
        _TI_SECTION_TPLS["data_flash" if flash else "data"],
        _TI_SECTION_TPLS["bss"],
        _TI_SECTION_TPLS["stacks"],
    ])

    # Component archives are linked on the command line; their .text/.data
    # land in the wildcard collectors above.  Named MPU ranges come later.

    for entry in args.domain:
        parts = entry.split(":", 1)
        dname = parts[0]
        dregion = parts[1] if len(parts) > 1 else "KERNEL_RAM"
        sections.append(f"""
    .domain_{dname} : {{
        _ulmk_domain_{dname}_start = .;
        *(.data.domain_{dname}*)
        *(.bss.domain_{dname}*)
        _ulmk_domain_{dname}_end = .;
    }} > {dregion}, type = NOLOAD
""")

    sections.append(_TI_SECTION_TPLS["user_pool"])

    if flash:
        # resetvector after .data so SMP stubs can follow without a cert hole.
        tail_path = os.path.join(args.arch_dir, "vectors_flash_tail.cmd.in")
        if os.path.exists(tail_path):
            sections.append("\n" + read_fragment(tail_path))
        if getattr(args, "smp", False):
            smp_path = os.path.join(args.arch_dir, "vectors_flash_smp.cmd.in")
            if os.path.exists(smp_path):
                sections.append("\n" + read_fragment(smp_path))
        seccfg_path = os.path.join(args.arch_dir, "vectors_flash_seccfg.cmd.in")
        if os.path.exists(seccfg_path):
            sections.append("\n" + read_fragment(seccfg_path))

    prologue_path = os.path.join(args.arch_dir, "prologue.cmd.in")
    if os.path.exists(prologue_path):
        prologue = read_fragment(prologue_path)
    else:
        prologue = _TI_C29_PROLOGUE

    return (
        prologue
        + "\n"
        + chip_memory
        + "\nSECTIONS\n{\n"
        + "".join(sections)
        + "\n}\n"
    )


def read_fragment(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def render_snippet(path: str, substitutions: dict) -> str:
    content = read_fragment(path)
    for key, val in substitutions.items():
        content = content.replace(f"@{key}@", val)
    return content


def parse_flags(chip_memory_ld: str) -> dict:
    """Extract HAVE_* flag values from the chip memory.ld as integers."""
    flags = {}
    for name in ("HAVE_CSA", "HAVE_CSA_CPU1", "HAVE_CSA_CPU2",
                 "HAVE_SMALL_DATA", "HAVE_BMHD"):
        m = re.search(rf"^\s*{name}\s*=\s*(\d+)\s*;", chip_memory_ld, re.MULTILINE)
        flags[name] = int(m.group(1)) if m else 0
    return flags


def main():
    ap = argparse.ArgumentParser(description="ulmk linker script generator")
    ap.add_argument("--chip-dir",   required=True)
    ap.add_argument("--arch-dir",   required=True)
    ap.add_argument("--kernel-dir", required=True)
    ap.add_argument("--snippets",   required=True)
    ap.add_argument("--output",     required=True)
    ap.add_argument("--dialect",    default="gnu",
                    choices=["gnu", "ti-c29"],
                    help="Linker dialect: gnu (default) or ti-c29")
    ap.add_argument("--core",       default="1",
                    help="Target core index for ti-c29 dialect (1|2|3)")
    ap.add_argument("--profile",    default="ram",
                    choices=["ram", "flash"],
                    help="C29 memory profile: ram (default) or flash")
    ap.add_argument("--smp",        action="store_true",
                    help="C29 flash: append secondary stub sections after CPU1")
    ap.add_argument("--app",        action="append", default=[],
                    metavar="NAME")
    ap.add_argument("--comp",       action="append", default=[],
                    metavar="NAME")
    ap.add_argument("--domain",     action="append", default=[],
                    metavar="NAME:REGION")
    args = ap.parse_args()

    # TI C29 path: different renderer, different input files.
    if args.dialect == "ti-c29":
        if getattr(args, "profile", "ram") == "flash":
            chip_memory_path = os.path.join(args.chip_dir, "memory_flash.cmd")
            if not os.path.exists(chip_memory_path):
                raise SystemExit(
                    f"flash profile requested but {chip_memory_path} missing")
        else:
            chip_memory_path = os.path.join(args.chip_dir, "memory.cmd")
            if not os.path.exists(chip_memory_path):
                # Fall back to memory.ld name if board uses it.
                chip_memory_path = os.path.join(args.chip_dir, "memory.ld")
        chip_memory = read_fragment(chip_memory_path)
        result = _render_ti_cmd(args, chip_memory)
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(result)
        print(f"[generate_ld.py] wrote {args.output} (dialect=ti-c29 core={args.core})",
              file=sys.stderr)
        return

    out = []

    # 1. Arch prologue
    out.append(read_fragment(os.path.join(args.arch_dir, "prologue.ld.in")))

    # 2. Chip MEMORY block
    chip_memory = read_fragment(os.path.join(args.chip_dir, "memory.ld"))
    out.append(chip_memory)

    flags = parse_flags(chip_memory)

    out.append("\nSECTIONS {\n")

    # 3. [optional] BMHD
    bmhd_path = os.path.join(args.chip_dir, "bmhd.ld.in")
    if flags["HAVE_BMHD"] and os.path.exists(bmhd_path):
        out.append(read_fragment(bmhd_path))

    # 4a. Vectors — arch-specific when present (RISC-V trap section)
    vectors_arch = os.path.join(args.arch_dir, "vectors.ld.in")
    vectors_kernel = os.path.join(args.kernel_dir, "vectors.ld.in")
    vectors_tables = os.path.join(args.kernel_dir, "vectors_tables.ld.in")
    if os.path.exists(vectors_arch):
        out.append(read_fragment(vectors_arch))
    elif flags["HAVE_BMHD"] and os.path.exists(vectors_tables):
        out.append(read_fragment(vectors_tables))
    else:
        out.append(read_fragment(vectors_kernel))

    # 4b. Kernel text (libulmk_kernel.a only)
    out.append(read_fragment(os.path.join(args.kernel_dir, "kernel_text.ld.in")))

    # 4c. Userspace text lower bound (per-component sections follow)
    out.append("    _ulmk_user_text_start = .;\n")

    # 4d. Per-component text snippets — one MPU-aligned section per component,
    #     selecting exclusively from libulmk_comp_<name>.a
    comp_snippet = os.path.join(args.snippets, "comp_text.ld.in")
    for comp in args.comp:
        out.append(render_snippet(comp_snippet, {"COMP_NAME": comp}))

    # 4e. Per-app code snippets (legacy ulmk_add_app path)
    app_snippet = os.path.join(args.snippets, "app_code.ld.in")
    for app in args.app:
        out.append(render_snippet(app_snippet, {"APP_NAME": app}))

    # 4f. Userspace runtime / orphan flash (libgcc, etc.)
    out.append(read_fragment(os.path.join(args.kernel_dir, "user_runtime.ld.in")))

    # 4g. Domain descriptor table (flash)
    out.append(read_fragment(os.path.join(args.kernel_dir, "domain_table.ld.in")))

    # 4h. Kernel data (libulmk_kernel.a only)
    out.append(read_fragment(os.path.join(args.kernel_dir, "kernel_data.ld.in")))

    # 4i. Kernel stacks
    out.append(read_fragment(os.path.join(args.kernel_dir, "kernel_stacks.ld.in")))

    # 4j. CSA pool (arch-specific)
    if flags["HAVE_CSA"]:
        out.append(read_fragment(os.path.join(args.arch_dir, "csa_pool.ld.in")))

    # 4k. Small-data areas (arch-specific, kernel-owned RAM)
    if flags["HAVE_SMALL_DATA"]:
        out.append(read_fragment(os.path.join(args.arch_dir, "small_data.ld.in")))

    # 4l. End of kernel static RAM
    out.append(read_fragment(os.path.join(args.kernel_dir, "kernel_ram_end.ld.in")))

    # 4m. Start of userspace static RAM (domains/stacks/pool must follow)
    out.append(read_fragment(os.path.join(args.kernel_dir, "user_ram_start.ld.in")))

    # 4n. Per-domain data snippets (includes auto-registered component domains)
    domain_snippet = os.path.join(args.snippets, "domain_data.ld.in")
    for entry in args.domain:
        parts = entry.split(":", 1)
        dname = parts[0]
        dregion = parts[1] if len(parts) > 1 else "KERNEL_RAM"
        out.append(render_snippet(domain_snippet,
                                  {"DOMAIN_NAME": dname, "DOMAIN_REGION": dregion}))

    # 4o. ISR stack (userspace MPU RAM — ISP before PRS elevation)
    out.append(read_fragment(os.path.join(args.kernel_dir, "isr_stack.ld.in")))

    # 4p. Userspace-accessible kernel BSS (root thread stack, board IPC globals)
    out.append(read_fragment(os.path.join(args.kernel_dir, "user_bss.ld.in")))

    # 4q. User pool (always last in KERNEL_RAM)
    out.append(read_fragment(os.path.join(args.kernel_dir, "user_pool.ld.in")))

    # 4r. Secondary DSPR CSA/ISP/park — AFTER KERNEL_RAM so VMA '.' is not
    #     left in 0x6xxx/0x5xxx (would corrupt user_ram_start / zero_words).
    if flags.get("HAVE_CSA_CPU1"):
        cpu1 = os.path.join(args.arch_dir, "csa_pool_cpu1.ld.in")
        if os.path.exists(cpu1):
            out.append(read_fragment(cpu1))
    if flags.get("HAVE_CSA_CPU2"):
        cpu2 = os.path.join(args.arch_dir, "csa_pool_cpu2.ld.in")
        if os.path.exists(cpu2):
            out.append(read_fragment(cpu2))

    out.append("\n} /* SECTIONS */\n")

    mem_sym = os.path.join(args.kernel_dir, "memory_symbols.ld.in")
    if os.path.exists(mem_sym):
        out.append(read_fragment(mem_sym))

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"[generate_ld.py] wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
